<template>
  <section class="hero">
    <div class="hero-copy">
      <span class="hero-eyebrow">{{ "Live Exhibition · Procedural Three.js" }}</span>
      <h1 class="hero-title">
        {{ "One reference image in." }}<br />
        <span class="grad">{{ "Procedural 3D" }}</span
        >{{ " model out." }}
      </h1>
      <p class="hero-sub">
        {{
          "From a single reference image, rebuild an editable procedural Three.js model — no imported meshes, all generated by TypeScript factory functions. Every exhibit documents the full prompt, reference material, and the few decisions that made or broke it."
        }}
      </p>
      <div class="cta-row">
        <RouterLink class="btn btn-primary" :to="`/${firstSlug}`">{{ "Enter Exhibit" }}</RouterLink>
        <a class="btn btn-star" :href="REPO_URL" target="_blank" rel="noopener noreferrer">
          {{ "★ Source Code" }}
        </a>
      </div>
      <ol class="pipeline" aria-label="Rebuild pipeline">
        <li><span class="pip-num">01</span>{{ "Reference" }}</li>
        <li class="pip-arrow" aria-hidden="true">→</li>
        <li><span class="pip-num">02</span>{{ "Analysis & Spec" }}</li>
        <li class="pip-arrow" aria-hidden="true">→</li>
        <li><span class="pip-num">03</span>{{ "Procedural Three.js" }}</li>
      </ol>
    </div>

    <!-- The turntable is the second grid column. It arrives as a slot so the page can
         keep a ref to it — hovering a gallery card jumps it to that exhibit. -->
    <slot name="stage" />
  </section>
</template>

<script setup lang="ts">
import { RouterLink } from "vue-router";
import { REPO_URL } from "~/site";

// Styles: src/styles/showcase/home-hero.css

defineProps<{ firstSlug: string }>();
</script>
